### PR TITLE
update code to use new retirement schema

### PR DESCRIPTION
**Pull request by camallen**
Move away from the `SetMemberSubject#retired_workflow_ids` instead use the `SubjectWorkflowCount#retired_at` field in data dumps and the `Subject#retired_for_workflow?` method.

### CODE REVIEW

**Comment by camallen** [comment]
@marten this needs to be in before we remove the `retired_workflow_ids` schema setup.

**Comment by marten** [comment]
I was working on something like this too, but hadn't reached a PR yet. Mine is going in this direction, but I don't mind rebasing on yours either:

```diff
   def retired_for_workflow?(workflow)
     if workflow && workflow.is_a?(Workflow) && workflow.persisted?
-      set_member_subjects.first.retired_workflow_ids.include?(workflow.id)
+      set_member_subjects.joins(:subject_workflow_counts)
+                         .where(subject_workflow_counts: {workflow_id: workflow.id})
+                         .where.not(subject_workflow_counts: {retired_at: nil})
+                         .any?
     else
       false
     end
```

and:

```diff
-  belongs_to_many :retired_workflows, class_name: "Workflow"
+  has_many :retired_subject_workflow_counts, -> { retired }, class_name: 'SubjectWorkflowCount'
+  has_many :retired_workflows, through: :retired_subject_workflow_counts, source: :workflow
   has_many :subject_workflow_counts, dependent: :destroy
   has_many :workflows, through: :subject_set

   def retire_workflow(workflow)
-    retired_workflows << workflow
-    save!
+    count = subject_workflow_counts.find_or_create_by!(workflow_id: workflow.id)
+    count.retire!
+  end
+
+  def retired_workflow_ids
+    retired_workflows.pluck(:id)
+  end
```

**Comment by camallen** [comment]
Right, should have asked. I was looking at the classification & subject dumps earlier and realised that they will be busted if we remove the prev schema. I kinda prefer your explicit relations to be fair but i won't get to work on this again till next week. If this PR is all good then can you just rebase over it?

**Comment by camallen** [comment]
Also make sure the subjects#set_member_subjects belong to a subject set that belongs to the workflow in question.

**Comment by marten** [comment]
Seems like specs fail because the controller spec still sets retiredness with `sms.retired_workflows`. If you change that the rest is LGTM.

**Comment by marten** [comment]
Or let me know if you want me to fix it up btw.

**Pull request merged**
