### PR TITLE
fetch serialised classification data from read replica

### PR DESCRIPTION
**Pull request by camallen**
move this read query load off the primary db to the replica

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by nciemniak** [comment]
Just an initial thought, I'm thinking it'd be good to add the `classification_serializer_data_from_replica` flag to this wiki page for future reference: https://github.com/zooniverse/panoptes/wiki/Feature-Flags

**Review by nciemniak — APPROVED** [review]
Code changes look good to me 👍 would just ask for documentation of the new feature flag in the wiki like I mentioned in previous comment.

Just one question - why is classification data a good candidate when it comes to retrieving data from the read replica? I vaguely agree with the choice, but off the top of my head can't think of the places where the api/classifications endpoint is hit in PFE and whether we need the data retrieved at that point to be *the most-up-to-date* data.

**Comment by camallen** [comment]
Added the flag docs - https://github.com/zooniverse/panoptes/wiki/Feature-Flags#classification_serializer_data_from_replica-on

> Just one question - why is classification data a good candidate when it comes to retrieving data from the read replica? I vaguely agree with the choice, but off the top of my head can't think of the places where the api/classifications endpoint is hit in PFE and whether we need the data retrieved at that point to be _the most-up-to-date_ data.

These end points aren't really used in PFE, rather they are used by some research teams to ingest their project classification data to their research databases for their own analysis. 

That said the `/incomplete` route is used by ASM (i believe) to save a users partially completed classification data so they can access it at a later point. The ASM project is complete so not using this feature any more.

**Comment by nciemniak** [comment]
Awesome, thanks for the info!

**Pull request merged**
