### PR TITLE
Workflow tutorials

### LINKED ISSUE #1730: Link tutorials to workflows
Related to #1726, Gravity Spy will have a couple workflows: one for beginners to the project and one for advanced classifiers. The different workflows should have separate tutorials. In the future, Notes for Nature will also need tutorials linked to workflows.

### PR DESCRIPTION
**Pull request by marten**
Allow linking tutorials with specific workflows, and allow querying tutorials filtered to a given workflow_id.

Fixes #1730 and #1726 

# Review checklist

* First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
* If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
* If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
* Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by parrish** [comment]
This looks good.  It's missing indexes on

tutorials:
  - kind

workflow_tutorials:
  - workflow_id
  - tutorial_id

After that, is this good to merge or should we coordinate with the migration?

**Comment by marten** [comment]
Added. We can merge, deploy and run that rake task just fine right now. Probably no additional tutorials will be created in the meantime (which then wouldn't be associated with a workflow), but we probably want to rerun the rake task once PFE is ready and deployed.

**Comment by parrish** [comment]
Looks good now :+1:

**Comment by srallen** [comment]
@marten now that workflow tutorials are in production on PFE, could you rerun the rake task to link workflows and tutorials in case someone has built a tutorial in the last month or so? Thanks.

**Comment by marten** [comment]
Done. Thanks for the reminder, I would've totally forgot otherwise.

**Pull request merged**
