### PR TITLE
Devise styles

### PR DESCRIPTION
**Pull request by srallen**
- Added base and form css style files for devise views that users may encounter.
- Added semantic layout with classes to devise views and partials, and minor updates to application.html.erb

### CODE REVIEW

**Comment by edpaget** [comment]
Two small things: 
+ Can the label for the login form say "User name or Email Address" ala the front-end instead of 'login'
+ Can we have the Zooniverse logo somewhere on the page?

**Comment by edpaget** [comment]
Also it looks like the password forms on the sign-up page got messed up?

screenshot from 2015-08-17 14-59-27

**Comment by srallen** [comment]
I'll take another look. You use Firefox?

**Comment by edpaget** [comment]
Yes.

**Comment by edpaget** [comment]
@srallen this looks fine on my home machine. I think I must have something misconfigured on my work computer.

**Comment by camallen** [comment]
looks good on my ubuntu machine using chrome & firefox. Slightly off topic...what should we do with the root index page? Redirect?

**Comment by edpaget** [comment]
Maybe redirect to a docs page?

**Comment by camallen** [comment]
@srallen can you please rebase this of the latest master?

**Comment by camallen** [comment]
@srallen i made some links on the index / landing page instead of redirects [here](https://github.com/camallen/Panoptes/commit/7602823d9ffac1912628f9985b8ca20062391df4). you could cherrypick them in and rebase as well too. there's been a lot of work on the repo since you started this branch.

**Comment by edpaget** [comment]
@camallen is there any reason that can't just be a seperate PR after this is merged?

**Comment by camallen** [comment]
not at all.

**Comment by srallen** [comment]
Cool, I'll take a look and get rebased with master.

**Pull request merged**
