### PR TITLE
raise project introduction limit to 5K

### PR DESCRIPTION
**Pull request by camallen**
Closes https://github.com/zooniverse/Panoptes-Front-End/issues/2239

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by zwolf** [comment]
Looks good, if 5000 characters is going to be enough. Did they provide a sample chunk o' text to measure?

**Comment by camallen** [comment]
Nope, just taking @vrooje 's suggestion of 5K from https://github.com/zooniverse/Panoptes-Front-End/issues/2239#issuecomment-214777704

**Comment by zwolf** [comment]
LGTM, then. Can always raise it again later in the unlikely event that's necessary.

**Comment by camallen** [comment]
5K should really be enough even with markup. That said you're right, we can always raise if needed.

**Pull request merged**
