### PR TITLE
don't dequque all for SGL

### PR DESCRIPTION
**Pull request by camallen**
avoid locking up the workers

### CODE REVIEW

**Comment by parrish** [comment]
Should we decrease the queue size in this case?

**Comment by parrish** [comment]
Part of the problem is that there's a race condition on trying to dequeue the same subject multiple times.

Maybe do a check that it's active before trying to dequeue it?

**Comment by camallen** [comment]
I'm not 100% sure about the flow on effects of shrinking the queues, to say 10/20, halving could work. 

A couple of page reloads (10 selected per time) and they'll be empty but the only refill on classification submission. So an empty queue will fallback to PG selection. It may be all fine while we've got a bigger db but when we scale down there may be ripple effects. Thoughts?

**Comment by parrish** [comment]
True.  I'll merge this and keep an eye on how it behaves.

**Pull request merged**
