### PR TITLE
Revert "Add Honeybadger call to get backtrace of enqueue location"

### PR DESCRIPTION
**Pull request by marten**
Reverts zooniverse/Panoptes#2550

Hasn't happened again in these past days. @camallen how often were these errors before?

### CODE REVIEW

**Comment by camallen** [comment]
Occasional though i managed to see it a few times. Noting that I only observed this when looking at I was looking at running jobs. Let's leave it for a little bit longer as it might be a sidekiq UI issue though i somewhat doubt that.

**Comment by camallen** [comment]
Also what's up with the extra revert commits?

**Comment by marten** [comment]
Not sure. I just hit the revert-PR button in Github. Happy to leave this in place for a while longer, just wanted to make sure we had a PR open to remind us to take it out.

**Comment by marten** [comment]
@camallen okay, well this didn't seem to help get stuff into HB. Shall we merge this?

**Pull request merged**
