### PR TITLE
disable increment_counters for SGL

### PR DESCRIPTION
**Pull request by camallen**
turn these off for now...we can look at getting a better counter working later.

### CODE REVIEW

**Comment by camallen** [comment]
Should i just put an if guard for the project on this instead?

**Comment by parrish** [comment]
Looks good.  I'll merge when the test passes

**Comment by parrish** [comment]
You mean an `if ENV['WHATEVER']` statement?  I think this is fine.

**Comment by camallen** [comment]
just skipping if the project_id == SGL project id so we don't have to recount everything later..

**Comment by parrish** [comment]
Ah.  Yeah, that'd be preferable

**Comment by camallen** [comment]
closed in favour of #1621

**Pull request closed without merging**
