### PR TITLE
Test out the speed of the subject selector using scientist

### PR DESCRIPTION
**Pull request by camallen**
Use scientist and feature flipping to test out subject queue selection in band and skip the queue state update problem.

This hopefully will fix a lot of the already seens issues users are having (from delayed queue updates) and this will also allow us to use queue's for targeted subject task allocation.

TODO:
- [ ] Think about dropping all non-logged in queues and enforcing a FK link on users for them.

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by camallen** [comment]
For some reason this hasn't passed the CI for the latest commit. Let's get the admin enabled PR in before merging this so i can rebase and force the CI to run.

**Comment by marten** [comment]
Rebase at your convenience.

**Comment by camallen** [comment]
rebased

**Comment by marten** [comment]
LGTM

**Comment by camallen** [comment]
I'm going to move this to 50% of the time instead of 100% just in case the load is too much.

**Pull request merged**
