### PR TITLE
Use Docker compose 1.3 alternate dockerfile

### PR DESCRIPTION
**Pull request by marten**
The only thing I'm not certain of is how Jenkins builds the production container. Does it use `rake configure:prod_docker` (which this branch removes) anywhere or was that just for local use?

### CODE REVIEW

**Comment by camallen** [comment]
Excellent stuff - been waiting for a while to use the alternate docker file feature. All prod builds will use the default expected `Dockerfile` in the root.

**Comment by marten** [comment]
Yeah, I just noticed it was released 18 june.

**Comment by marten** [comment]
@camallen I assume that's a LGTM?

**Comment by camallen** [comment]
Happy days!

**Pull request merged**
