### PR TITLE
Subjects in classifications

### PR DESCRIPTION
**Pull request by edpaget**
Address Brian's concerns from #512. Hide set_memebr_subjects entirely.
I'll need to update the cellect_panotpes driver to use only subjects

### CODE REVIEW

**Comment by edpaget** [comment]
Merge after #518

**Comment by camallen** [comment]
@ed - can you rebase? Also what role do the set member subjects play now? Just placeholders for counters? How / when will they get updated?

**Comment by edpaget** [comment]
Rebased. The Set Member Subjects are going to act as a Many-To-Many join table for Subject -> SubjectSet, with two additional columns for the classification count and their active state. The only clients that will need to touch them are ones that want to retire subjects based on some external criteria.

**Comment by camallen** [comment]
I guess this depends on load testing / usage patterns but I think we should still use the active state on `set_member_subjects` when loading via cellect to keep the memory footprint smaller across all our cellect nodes.

**Comment by camallen** [comment]
Also do you want to remove this migration and just keep the schema or leave it and squash it on the next migration?

**Comment by edpaget** [comment]
Yeah I was intending to do that too. I'm redoing the cellect adapter to use ActiveRecord instead of just sql strings, so we can benefit from prepared/cached statements.

**Comment by edpaget** [comment]
Good point I'll squash it.

**Comment by camallen** [comment]
Nice!

**Comment by edpaget** [comment]
I also need to update the docs.

**Pull request merged**
