### PR TITLE
Remove cassandra

### LINKED ISSUE #1458: Remove cassandra

### PR DESCRIPTION
**Pull request by marten**
Fixes #1458

### CODE REVIEW

**Comment by camallen** [comment]
looks like the db create step in travis failed...https://github.com/zooniverse/Panoptes/blob/1a5a5bd12117773f89ca0c91cdc4ad827c28af8d/.travis.yml#L8

Should we use the sql schema for creating the db now?

**Comment by marten** [comment]
Nah, the silver searcher just didn't look into yml files so I missed the cequel reference there.

**Comment by camallen** [comment]
Want to remove the cassandra service addon for travis too?

Also i think we should just use `RACK_ENV=test bundle exec rake configure:travis db:create db:structure:load` instead of running the migrations now we have a sql dump that should work.

**Comment by marten** [comment]
Good idea, will make sure the structure file keeps working too.

**Pull request merged**
