### PR TITLE
add lifecycled at migration for classifications

### LINKED ISSUE #1517: add lifecycled_at field to classification
On the event where classification saves but can't be queued for background work. We'd set the `lifecycled_at` field on successful classification lifecycle processing and add a sidetiq scheduled job to reprocess any that haven't been set.

### PR DESCRIPTION
**Pull request by camallen**
closes #1517 adds a lifecycled at timestamp, that is updated in the lifecycle. Also have a rake task to backfill, i wasn't sure if this will break the app adding in this col, anyway to pre-load the cols on the model to not break?

### CODE REVIEW

**Comment by marten** [comment]
To close #1517 I think we should also add the sidetiq worker that retries stuff. We can do that in another branch though.

LGTM

**Comment by camallen** [comment]
i should probably make that worker

**Comment by camallen** [comment]
@marten is there anything we can do to stop the col add busting the query cache here?

**Comment by marten** [comment]
Don't think so, apart from trying to restart puma & sidekiq as quickly as possible.

**Comment by camallen** [comment]
yeah - that's what I thought too..merging.

**Comment by marten** [comment]
Here's hoping https://github.com/rails/rails/pull/22170 gets merged for Rails 5.

**Pull request merged**
