### PR TITLE
Subject workflow status resource

### LINKED ISSUE #1886: New API Route to retrieve retired subjects
I need a route that lets me retrieve the subjects that have been retired in a given workflow, optionally since a given datetime. Zach and I discussed this a while ago and I forgot to create an issue about it for tracking purposes.

### PR DESCRIPTION
**Pull request by camallen**
closes #1886 - expose the SubjectWorkflowStatus resource via the api

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by marten** [comment]
Renaming the table can't really be done while the app is running. Are we sure we want to do that, vs just setting self.table_name inside the AR model?

**Comment by camallen** [comment]
Much better idea - i'll do that.

**Comment by camallen** [comment]
@astopy do we need this out this week?

**Comment by astopy** [comment]
@camallen As soon as we can, but it's not vital for it to be this week.

**Comment by marten** [comment]
LGTM

**Pull request merged**
