### PR TITLE
Upgrade to Ruby 2.3.0

### PR DESCRIPTION
**Pull request by parrish**
Primarily to fix [this bug](https://app.honeybadger.io/projects/40595/faults/23124244) and the performance hit it causes.

2.3 also includes [the lonely operator](https://bugs.ruby-lang.org/issues/11537) and other performance improvements.

### CODE REVIEW

**Comment by camallen** [comment]
LGTM, how does it fix that bug? 

Lonely operator looks interesting, i wonder what Sandi Metz would say about that.

**Comment by marten** [comment]
I've previously used https://github.com/raganwald/andand for that lonely operator. It's a blessing and a curse really. You have to be really careful with it, or you'll just end up pushing nils everywhere and you can't debug shit anymore. It's awesome on the debug console though.

**Comment by parrish** [comment]
This is the bug in question: https://bugs.ruby-lang.org/issues/10871

**Comment by parrish** [comment]
This is the bug in question: https://bugs.ruby-lang.org/issues/10871

**Pull request merged**
