### PR TITLE
split the travis build up on different concerns

### PR DESCRIPTION
**Pull request by camallen**
Split the spec tasks up to the concurrent build limit on travis (currently 5) to decrease the total run time (prev 23m, now ~7m).

### CODE REVIEW

**Comment by marten** [comment]
The main thought I had is that we'll need to be pretty vigilant about adding directories (for instance I'm adding `spec/operations` in a PR, which wouldn't get picked up on CI. Any thoughts on how to fail the build in such case?

**Comment by camallen** [comment]
Yeah, a good point. I can't see an easy way to match and split up the build. Vigilance? We could try gems that do this for us too.

**Comment by marten** [comment]
Maybe a step that just checks the directories against a known list, and fails if it doesn't match? That'd be good enough for me.

**Comment by marten** [comment]
Hey, what happened to the Travis build status on this branch? All I see now if Hound's status.

**Comment by camallen** [comment]
Not sure, I just rebased this to start adding the checks.

**Comment by camallen** [comment]
Ok - this should be good to go. 

I've added a list of know spec directories and compared this to a current spec dir listing before running the specs, see [this run](https://travis-ci.org/zooniverse/Panoptes/builds/109367464) for a failure.

The known file entries and the actual spec cmds are not enforced. So when adding new spec directories the updating user will have to include new spec dirs in the travis commands **AND** add them to the `known_dirs.txt` file.

**Pull request merged**
