### PR TITLE
Squash databse migrations into a single script

### PR DESCRIPTION
**Pull request by edpaget**
This just tidies the migrations directory. Since we're not actually migrating any preexisting data yet, we don't need to have 100+ files. This will make it easier to see and find migrations that actually do migrate data when we need to handle that.

### CODE REVIEW

**Comment by camallen** [comment]
@edpaget out of interest did you use a gem for this?

**Comment by edpaget** [comment]
No all you have to do is copy the `db/schema.rb` file.

**Comment by camallen** [comment]
cool.

**Comment by edpaget** [comment]
Yeah I just realized that when I was trying to find a migration I had just generated. I think we should regularly squash migrations until we're writing ones that need to be mindful of pre-existing data.

**Comment by camallen** [comment]
will do.

**Pull request merged**
