### PR TITLE
Allow unicode chars in the login field

### PR DESCRIPTION
**Pull request by camallen**
Putting this out there since it cropped up as an error on login. Adding basic support for unicode characters in login, however this may break @ - mentions in talk. 

I'm voting yes especially to target non-ascii char based languages over the world. @mrniaboc thoughts?

### CODE REVIEW

**Comment by edpaget** [comment]
I 100% disagree with this since this will make any @-ing system totally unworkable. The ASCII character set is the lowest common denominator in terms of computer input. Anyone can type it on pretty much any device. 

As soon as we allow arbitrary unicode characters in login names, then we segregate who who can @ to people whose name characters are in a set you can easily type. 

We have display names so people can already choose to be represented in their profile and in the larger name that appears next to their talk posts in whatever form they want to be.

**Comment by DarrenMcRoy** [comment]
I'm really with Ed on this one. We should do whatever Twitter already does here. They seem to have no issues with being global. :+1:

**Comment by edpaget** [comment]
I addition, this would allow project URL spoofing to happen. If we allows any unicode character in URLs then users wouldn't know whether zooniverse.org/#/projects/zooniverse/Galaxy-Zoo takes them to our Galaxy Zoo page or another user's page who's using Cyrillic characters to look like zooniverse.

**Comment by astopy** [comment]
I’m with Ed. This will have all kinds of unpredictable security implications.

**Comment by camallen** [comment]
Ah - The latter point about mimicking other accounts is alarming, that will open up a can of worms. I going to close this and we'll deal with existing users on a case by case basis.

**Pull request closed without merging**
