### PR TITLE
re-add classification indexes concurrently

### PR DESCRIPTION
**Pull request by camallen**
concurrently create indexes to track created_at, lifecycle and user_id indexes (recents)

Time on my dev machine..
```
== 20160114135531 ReAddClassificationIndexes: migrating =======================
-- add_index(:classifications, :created_at, {:algorithm=>:concurrently})
   -> 15.3824s
-- add_index(:classifications, :user_id, {:algorithm=>:concurrently})
   -> 18.1663s
-- add_index(:classifications, :lifecycled_at, {:where=>"(lifecycled_at IS NULL)", :algorithm=>:concurrently})
   -> 3.0346s
== 20160114135531 ReAddClassificationIndexes: migrated (36.5836s) =============
```

### CODE REVIEW

**Comment by marten** [comment]
LGTM, are there a bunch of comments that should be removed too?

**Comment by camallen** [comment]
yeah - good catch will remove.

**Comment by camallen** [comment]
@marten updated with a new partial incomplete index too

**Comment by marten** [comment]
LGTM

**Pull request merged**
