### PR TITLE
cellect api caching

### PR DESCRIPTION
**Pull request by camallen**
Add some caching headers to these end points (i wasn't sure about the max-age values)

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by parrish** [comment]
Looks good, but I'm not 100% on the caching, particularly with a file cache-store.  Multiple requests per-minute should only occur when something goes wrong with cellect (or we're bringing up multiple nodes simultaneously).  Now that the loading can't be re-entrant, we should be good without it -- I imagine caching large sets have a fair bit of overhead.

What do you think?

**Comment by camallen** [comment]
These cache directives should just be telling the nginx reverse proxy (and intermediate ones) that it can cache the response and thus avoid hitting the rails app. It's currently only using the rails file store cache (probably should move to redis/memcache) for the workflow details as i thought the larger / slower subjects responses could swamp the internal file store (moving to redis cache should help with this).

screen shot 2016-08-17 at 09 50 30

I figured anything to avoid re-calculating / speeding these up would be beneficial for the rails app. IMHO these responses should be cacheable at the HTTP layer.

**Comment by astopy** [comment]
I'm pretty sure that we don't have caching turned on in nginx or cloudfront for panoptes, so this won't have any effect without also setting those up.

**Comment by camallen** [comment]
you are right re the nginx config but we certainly could be adding nginx cache directives for the these cellect routes.

**Comment by parrish** [comment]
Yeah, that's a pretty gnarly request.  Since a large chunk of that time is just data transfer, maybe we should enable GZIP on it? `Rack::Deflater` provides middleware for it: https://github.com/rack/rack/blob/master/lib/rack/deflater.rb

**Comment by camallen** [comment]
I'll look into adding compression, probably via the nginx reverse proxy though and report back.

**Comment by marten** [comment]
Keep in mind too that this would be used mostly from internal traffic. Compression would still help, but by a much smaller fraction than calling it from the office.

**Comment by parrish** [comment]
👍 Ready to go, or does nginx still need setup?

**Comment by camallen** [comment]
Ready to roll, i'll add nginx later.

**Pull request merged**
