### PR TITLE
Kafka classification stream using AMS instead of RestPack

### LINKED ISSUE #1072: Include subjects in the Kafka classification JSONs
For the SWAP integration with Kafka the worker needs to have access to the metadata of the subjects of the classification. It needs that to check if a subject is a training subject. To avoid dealing with caching  and making API calls to fetch the metadata, it's easiest if we post the subject JSON along with the classification straight into Kafka.

### PR DESCRIPTION
**Pull request by marten**
The V1Adapter I've added is compatible (for this case, in general there might be a few minor differences with RestPack, haven't exhaustively checked) with output from RestPack. The V1Adapter is basically a copy of an older AMS adapter from before they started working towards JSON-API 1.0, with a few naming changes to be like RestPack.

AMS has a built-in JsonApi adapter (which I've made default in initializer) which follows the 1.0 spec for JSON-API.

Apart from that, AMS "just works" with things like belongs_to_many, has support for virtual associations as well, just define a method on the serializer and state at the top that it has_many or belongs_to that method name.

Fixes #1072

### CODE REVIEW

**Comment by edpaget** [comment]
This looks great.

**Comment by camallen** [comment]
yeah - i like it

**Comment by marten** [comment]
Awesome, I'll expand the KafkaSubjectSerializer and poke you for a final review.

**Comment by marten** [comment]
Added metadata to subject serialization, should be good enough for Nero now. LGTY?

**Comment by edpaget** [comment]
:shipit: once travis finishes.

**Pull request merged**
