### PR TITLE
Expose ports for easier debugging

### PR DESCRIPTION
**Pull request by marten**
I'm happy to change the ports if it collides with anyone's docker containers, but this just makes it so much easier to open a postgresql shell etc. I keep making this change and then not committing it, so I figured it'd poll opinions on a PR.

### CODE REVIEW

**Comment by camallen** [comment]
happy for this to go in...i think default ports make sense

**Comment by marten** [comment]
Cool. It might collide with linux-folk since you can use docker straight on your machine, and you might have PG running locally too?

**Comment by astopy** [comment]
Maybe don't use the default ports to avoid it colliding?

**Comment by marten** [comment]
@astopy do you know what IP exposed ports bind to by default? If not 127.0.0.1, can we make that so, would help accidentally exposing a database dump?

**Comment by astopy** [comment]
You can add the IP in the port specification (as IP:host_port:container_port). It’ll bind to 0.0.0.0 by default I think, but if you change it to 127.0.0.1 that’ll probably break for docker-machine.

**Comment by marten** [comment]
Just merging this then. Feel free to change the ports if it bugs anyone.

**Pull request merged**
