### PR TITLE
Respect page_size limits in subject selector

### PR DESCRIPTION
**Pull request by camallen**
ensure the page size query param hits the selectors and some minor improvements / refactoring.

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by marten** [comment]
I found this condition really hard too follow in terms of which number will be chosen in the end. Are you trying to clamp the given limit between a min and a max? If so, could you write it like `[min, limit, max].sort[1]` or (even better) add a clamp refinement?

**Comment by camallen** [comment]
agree, i'll checkout your range clamp refinement.

**Comment by marten** [comment]
I've done it like this before, but that should've been a refinement module these days.

https://github.com/roqua/roqua-support/blob/master/lib/roqua/core_ext/fixnum/clamp.rb

**Comment by camallen** [comment]
updated - thanks for the tip on range claming.

**Pull request merged**
