### PR TITLE
raise connection error when no cellect hosts available

### PR DESCRIPTION
**Pull request by camallen**
handle the case where the cellect node_set is empty and thus the returned host will be nil.

### CODE REVIEW

**Comment by marten** [comment]
LGTM, but I feel like all this should really be done by the cellect client object (and thus be extracted to the cellect gem)

**Comment by camallen** [comment]
I think it's valid behavior for a client to return nil if there are no hosts...it's up to the user to figure out what todo in that scenario, ignore / raise.

**Comment by camallen** [comment]
@marten Ah - do you mean move the client code from here to the gem? We could look at that.

**Comment by marten** [comment]
Yes. But again, fine to merge until then

**Pull request merged**
