### PR TITLE
Set text task answer label to default value

### PR DESCRIPTION
**Pull request by zwolf**
Instead of looking for a nonexistent answer label for a text task, just set it to "text". 

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by marten** [comment]
Why don't text tasks have a question?

**Comment by zwolf** [comment]
They do, it's the task's "instruction". Why it's called that instead, I don't know. They also have "help". They don't have an answer, however, which is why looking for it's label caused the exception.

**Comment by marten** [comment]
I'm sure it's just me being wrong here, but isn't https://github.com/zwolf/Panoptes/blob/85ae87132e0b4afd294b207fb59ca79f6b762eb2/lib/formatter/csv/annotation_for_csv.rb#L124 the line that was being called, which looks up the "instruction"?

**Comment by zwolf** [comment]
Task label is the value for the question/instruction. Answer label is the value for the answer, which does not exist for fill-in-the-blank type Text questions.

**Comment by marten** [comment]
But... aren't you removing task_label here?

**Comment by zwolf** [comment]
yuuuuuuuuup. Looks like I mixed them up from the beginning. Come to think of it, #text doesn't call for answer label translation at all, which is where this error was being thrown.

**Pull request closed without merging**
