### PR TITLE
Form project slugs to include owner name

### PR DESCRIPTION
**Pull request by parrish**
As discussed in #1139

I'm not sure if/when we want this to go, but it's a pretty straightforward change.  Of course, it'll require updating the existing records as well as the front end.

### CODE REVIEW

**Comment by edpaget** [comment]
I was planning to leave them as two separate fields on the resource (`slug` and `owner_name`), so we wouldn't have to regenerate all the existing slugged fields. 

I created: https://github.com/zooniverse/Panoptes/pull/1208, so project resources could eager load the owning user group and just use the name field instead of having to handle both owner types and make an additional database call.

**Comment by parrish** [comment]
That's less useful than a static field -- talk would still be calling the API on every comment render if it needs to be dynamically generated.

**Comment by edpaget** [comment]
Why couldn't talk just include the owner_name field in the project response?

**Comment by edpaget** [comment]
Actually nevermind, I like your solution better. I'm going to send you a PR to you PR to take care of the user_group stuff.

**Comment by parrish** [comment]
Basically talk needs to be able to point users to front-end endpoints -- that's not possible at the moment without having to either add more foreign tables or consume the API -- both of which aren't ideal.  If projects stored either a fully formed slug (or slug + owner_name) then this would work

**Comment by edpaget** [comment]
Cool that make sense. I send you a super trivial patch to just handle the user group case https://github.com/parrish/Panoptes/pull/2

**Comment by edpaget** [comment]
:+1: Will merge as soon as travis finishes.

**Pull request merged**
