### PR TITLE
Adds a case insensitive index on user login and display name for LIKE queries

### PR DESCRIPTION
**Pull request by parrish**
Used by zooniverse/Talk-Api#90 for autocompleting usernames.

### CODE REVIEW

**Comment by parrish** [comment]
If you'd rather avoid casting to `::text` and use `varchar_pattern_ops` instead, I can rewrite this as an `execute` -- apparently schema_plus_pg_indexes always casts `case_insensitive` to `::text` for some reason.

**Comment by marten** [comment]
I have absolutely no idea about the characteristics of those operators, so I'm fine with any of them until proven otherwise :P

LGTM

**Comment by parrish** [comment]
@marten: Looks like this picked up conflicts on db/structure.sql so I recreated the commit

**Comment by parrish** [comment]
The structure.sql file is fixed now by the way.

**Comment by camallen** [comment]
@parrish i may be missing something but we already have 2 indexes ([here](https://github.com/zooniverse/Panoptes/blob/36b11e0cd805a71e556bd791ce4942ebd8a8b5a9/db/structure.sql#L2465) & [here](https://github.com/zooniverse/Panoptes/blob/36b11e0cd805a71e556bd791ce4942ebd8a8b5a9/db/structure.sql#L2486)) that support these like queries.

```
irb(main):002:0> User.where("lower(login) like 'cam'").explain
=> EXPLAIN for: SELECT "users".* FROM "users" WHERE (lower(login) like 'cam')
                                     QUERY PLAN
------------------------------------------------------------------------------------
 Index Scan using index_users_on_login on users  (cost=0.43..8.45 rows=1 width=445)
   Index Cond: (lower((login)::text) = 'cam'::text)
   Filter: (lower((login)::text) ~~ 'cam'::text)
(3 rows)

irb(main):003:0> User.where("lower(display_name) like 'cam'").explain
=> EXPLAIN for: SELECT "users".* FROM "users" WHERE (lower(display_name) like 'cam')
                                        QUERY PLAN
-------------------------------------------------------------------------------------------
 Index Scan using index_users_on_display_name on users  (cost=0.43..8.45 rows=1 width=445)
   Index Cond: (lower((display_name)::text) = 'cam'::text)
   Filter: (lower((display_name)::text) ~~ 'cam'::text)
(3 rows)

irb(main):004:0> User.where("lower(login) like 'cam' or lower(display_name) like 'cam'").explain     
=> EXPLAIN for: SELECT "users".* FROM "users" WHERE (lower(login) like 'cam' or lower(display_name) like 'cam')
                                               QUERY PLAN
---------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on users  (cost=8.88..16.89 rows=2 width=445)
   Recheck Cond: ((lower((login)::text) ~~ 'cam'::text) OR (lower((display_name)::text) ~~ 'cam'::text))
   Filter: ((lower((login)::text) ~~ 'cam'::text) OR (lower((display_name)::text) ~~ 'cam'::text))
   ->  BitmapOr  (cost=8.88..8.88 rows=2 width=0)
         ->  Bitmap Index Scan on index_users_on_login  (cost=0.00..4.44 rows=1 width=0)
               Index Cond: (lower((login)::text) = 'cam'::text)
         ->  Bitmap Index Scan on index_users_on_display_name  (cost=0.00..4.44 rows=1 width=0)
               Index Cond: (lower((display_name)::text) = 'cam'::text)
(8 rows)
```

**Comment by parrish** [comment]
Looks like it was the lack of the wildcard in your query that caused the query planner to use a different index.  (These queries are all rooted `LIKE` queries, by the way)

``` sql
explain analyze verbose

select * from users where lower(login) like 'cam%' and lower(display_name) like 'cam%' limit 5
```
``` sql
Limit  (cost=0.44..48.82 rows=1 width=890) (actual time=0.159..0.334 rows=5 loops=1)
  Output: id, email, encrypted_password, reset_password_token, reset_password_sent_at, remember_created_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, created_at, updated_at, hash_func, password_salt, display_name, zooniverse_id, credited_name, classifications_count, activated_state, languages, global_email_communication, project_email_communication, admin, banned, migrated, valid_email, project_id, beta_email_communication, login, unsubscribe_token, api_key, ouroboros_created, subject_limit, private_profile, tsv, upload_whitelist
  ->  Index Scan using index_users_on_lower_names on public.users  (cost=0.44..48.82 rows=1 width=890) (actual time=0.155..0.320 rows=5 loops=1)
        Output: id, email, encrypted_password, reset_password_token, reset_password_sent_at, remember_created_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, created_at, updated_at, hash_func, password_salt, display_name, zooniverse_id, credited_name, classifications_count, activated_state, languages, global_email_communication, project_email_communication, admin, banned, migrated, valid_email, project_id, beta_email_communication, login, unsubscribe_token, api_key, ouroboros_created, subject_limit, private_profile, tsv, upload_whitelist
        Index Cond: ((lower((users.login)::text) ~>=~ 'cam'::text) AND (lower((users.login)::text) ~<~ 'can'::text) AND (lower((users.display_name)::text) ~>=~ 'cam'::text) AND (lower((users.display_name)::text) ~<~ 'can'::text))
        Filter: ((lower((users.login)::text) ~~ 'cam%'::text) AND (lower((users.display_name)::text) ~~ 'cam%'::text))
Planning time: 0.451 ms
Execution time: 0.395 ms

```

**Pull request merged**
