### PR TITLE
Improve container startup times 

### PR DESCRIPTION
**Pull request by camallen**
Improve container startup times: 
1. avoid building at startup of the container
0. setup the tmp pid dirs at build time

## TODO
- [x] test this builds and works correctly locally

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by adammcmaster** [comment]
I think we'll need to put the `cp` command back on startup in Kubernetes, otherwise it'll mount an empty volume over the compiled assets.

**Comment by camallen** [comment]
> I think we'll need to put the `cp` command back on startup in Kubernetes, otherwise it'll mount an empty volume over the compiled assets.

I assume we can do that on the container startup lifecycle? https://github.com/zooniverse/caesar/blob/8d8b5d31d65b84a47e30cea5ccd77776ca5b4549/kubernetes/deployment-production.tmpl#L182

**Comment by adammcmaster** [comment]
Yup – actually, if we just don't merge #3326 it should be fine.

**Comment by camallen** [comment]
> Yup – actually, if we just don't merge #3326 it should be fine.

Up to you, we can revert that later after this is tested properly.

**Comment by adammcmaster** [comment]
I've closed it – if you and Zach could test/deploy this next week that'd be good.

**Comment by adammcmaster** [comment]
I think this is actually blocking staging deploys on K8, because it takes long enough that the liveness probe kills the container.

**Comment by camallen** [comment]
I've tested this locally and it's working. Much faster on boot times, I'll take responsibility for fixes in Azure staging env.

**Pull request merged**
