### PR TITLE
remove unrecognised cops in .rubocop.yml

### PR DESCRIPTION
**Pull request by camallen**
using the Gemfile robocop (0.87.1) I get, removing these fixes it. Noting i also get these errors with the latest version (0.89) https://rubygems.org/gems/rubocop/
```
Error: unrecognized cop Layout/EmptyLinesAroundAttributeAccessor found in .rubocop.yml, unrecognized cop Lint/DeprecatedOpenSSLConstant found in .rubocop.yml, unrecognized cop Lint/MixedRegexpCaptureTypes found in .rubocop.yml, unrecognized cop Style/AccessorGrouping found in .rubocop.yml, unrecognized cop Style/BisectedAttrAccessor found in .rubocop.yml, unrecognized cop Style/RedundantAssignment found in .rubocop.yml, unrecognized cop Style/RedundantFetchBlock found in .rubocop.yml, unrecognized cop Style/RedundantRegexpCharacterClass found in .rubocop.yml, unrecognized cop Style/RedundantRegexpEscape found in .rubocop.yml, unrecognized cop Style/SlicingWithRange found in .rubocop.yml
```
# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by camallen** [comment]
hound linter CI failing https://github.com/zooniverse/panoptes/pull/3460#pullrequestreview-477733952

**Comment by nciemniak** [comment]
It's still not clear to me why hound is not able to recognize those new cops, the warning I get implies that `Layout/EmptyLinesAroundAttributeAccessor (0.83)` was introduced in version 0.83. May be the case that hound is unable to recognize [pending cops](https://docs.rubocop.org/rubocop/versioning.html#pending-cops), which are introduced between major versions. Also strange to me that I'm getting the error locally on vs code but you're not, maybe it's got something to do with one of the other rubocop gems used (rubocop-ast, rubocop-rails, etc).

When I remove that cop, then open up a shell on my local Panoptes docker container and run the command `rubocop`, I get the same warning that I get in vs code:

> The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file: - Layout/EmptyLinesAroundAttributeAccessor (0.83) 

To work around this type of warning coming up, I'm thinking we can just enable all new cops of this sort (or alternatively disable, but it seems like we're leaning towards enabling all) with:
```
AllCops:
  NewCops: enable
```

**Comment by camallen** [comment]
Thanks @nciemniak - I won't rule out me doing something stupid here :(

Yes to allcops enable 👍 that sounds useful and more. Feel free to push that change to this PR and if it works for you then merge :)

**Comment by nciemniak** [comment]
Awesome, doing it.

**Pull request merged**
