### PR TITLE
Guard retirement

### PR DESCRIPTION
**Pull request by parrish**
Scenario is:
  - 3 people classify the same subject simultaneously.
  - The subject will retire after the next classification
  - The subject will attempt to retire and dequeue 3 times

This just adds a check to ensure it's not already retired.

I'm sure it's possible for a race condition to allow multiple retirements in cases of very high concurrency, but this should take care of the majority of them.

### CODE REVIEW

**Comment by parrish** [comment]
Also, in regards to #1630, everything still holds other than the dequeuing.

**Comment by camallen** [comment]
LGTM. @parrish Can you elaborate on the "everything still holds"?

**Comment by parrish** [comment]
In terms of preventing multiple attempts to retire the same subject.  E.g. it won't send multiple remove requests to cellect, it won't publish it multiple times, etc.

**Comment by marten** [comment]
LGTM

**Pull request merged**
