### PR TITLE
Increase pod count for staging

### PR DESCRIPTION
**Pull request by adammcmaster**
Avoid downtime when scaling/upgrading the cluster.

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by adammcmaster** [comment]
RollingUpdate appears to be the default:

```
$ kubectl describe deploy panoptes-production-app  | grep Strategy
StrategyType:           RollingUpdate
RollingUpdateStrategy:  25% max unavailable, 25% max surge
```

Did you specifically want to use 1 and 0 as the surge/unavailable limits instead of percentages?

**Comment by camallen** [comment]
> RollingUpdate appears to be the default:
> 
> ```
> $ kubectl describe deploy panoptes-production-app  | grep Strategy
> StrategyType:           RollingUpdate
> RollingUpdateStrategy:  25% max unavailable, 25% max surge
> ```
> 
> Did you specifically want to use 1 and 0 as the surge/unavailable limits instead of percentages?

I'm fine with percentages, basically we need 0 pods unavailable during the rollout.

**Comment by adammcmaster** [comment]
👍 That should be what it's already doing.

**Comment by adammcmaster** [comment]
Still not sure why we were seeing downtime for staging though, in that case.

**Comment by adammcmaster** [comment]
Oh, I bet draining a node doesn't trigger a rolling update. I think that's what I was thinking when I opened this PR – having an extra replica would stop the service going down if the Kubernetes node gets taken out of service. It's not really a big deal since it affects staging, but the Pingdom alerts annoy me.

**Comment by camallen** [comment]
> Oh, I bet draining a node doesn't trigger a rolling update. I think that's what I was thinking when I opened this PR – having an extra replica would stop the service going down if the Kubernetes node gets taken out of service. It's not really a big deal since it only affects staging, but the Pingdom alerts annoy me.

so before draining we would scale the replica count (assuming it goes to another node) and then drain, downscale the replica?

**Comment by adammcmaster** [comment]
Not exactly. Nodes get drained automatically all the time due to autoscaling, so the idea here is to just always have at least two pods running to avoid any disruption from that.

**Comment by camallen** [comment]
> Not exactly. Nodes get drained automatically all the time due to autoscaling, so the idea here is to just always have at least two pods running to avoid any disruption from that.

This sounds like we need pod disruption budgets for these services, https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-scheduler#plan-for-availability-using-pod-disruption-budgets

**Pull request closed without merging**
