### PR TITLE
remove the GIN index on subject ids

### PR DESCRIPTION
**Pull request by camallen**
Most likely fastupdate in batches was causing the db problems, http://www.postgresql.org/docs/9.1/static/gin-implementation.html

### CODE REVIEW

**Comment by edpaget** [comment]
Should we replace it with a gist index?

**Comment by edpaget** [comment]
Or not worry for now.

**Comment by camallen** [comment]
I am thinking this is tied to #292 and we can probably solve this using different DB technology.

**Comment by edpaget** [comment]
Sounds good.

**Pull request merged**
