### PR TITLE
Update to Rails 4.2.5.1

### PR DESCRIPTION
**Pull request by marten**

### CODE REVIEW

**Comment by marten** [comment]
It passed, but why in heavens name did that suddenly take 44 minutes to test?

**Comment by camallen** [comment]
I've got it on my list to do this https://docs.travis-ci.com/user/speeding-up-the-build/

**Comment by marten** [comment]
If we don't already, https://docs.travis-ci.com/user/caching/ would be a
simple first step.

On Mon, Jan 25, 2016 at 10:19 PM, Campbell Allen <notifications@github.com>
wrote:

> I've got it on my list to do this
> https://docs.travis-ci.com/user/speeding-up-the-build/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes/pull/1641#issuecomment-174695764>.
>



-- 
- Marten

**Comment by camallen** [comment]
https://github.com/zooniverse/Panoptes/blob/bf21e3f6b7784c214b33d1a99361fe13294175d1/.travis.yml#L2

**Pull request merged**
