### PR TITLE
Add rack-timeout using default settings

### PR DESCRIPTION
**Pull request by camallen**
Supersedes #1055    

Adds react timeout with a default of 15s to process a request.  Also bump gem minor updates lock mysql2 gem minor updates that won't build. Hopefully this will help with the stuck puma thread while we figure out a way to fix it.

### CODE REVIEW

**Comment by edpaget** [comment]
What kind of error does rack::timeout throw without any `rescue_from`? I think the error it raises will be uncaught leading to a 50x error type. If we make sure the error is 408, the frontend has code to catch and retry.

**Comment by camallen** [comment]
500's by the looks, we can catch it and return a different error but need to take care that we don't get stuck there...https://github.com/heroku/rack-timeout#errors

**Comment by camallen** [comment]
what does the front end do on 500's now?

**Comment by edpaget** [comment]
Shows `Error: 0`. I don't think its necessarily reasonable to retry on 50x requests since they indicate an internal server error, whereas certain 40x errors are recoverable.

**Comment by edpaget** [comment]
I had a local branch where I was working on rescuing and returning. I think I got hung up figuring out tests for it.

**Comment by edpaget** [comment]
Nevermind looks like I don't have it anymore. I don't mind merging this in and figuring out the proper handling later.

**Comment by camallen** [comment]
I was just going to say let's get this in and see what happens. I think these stuck threads that would raise the timeout error never return anyway. they get stuck looking for a FUTEX that is never set so the associated client request ends up timing out i assume.

**Comment by camallen** [comment]
I see this as a stop gap, if it's causing too many problems we can rip it out and look at another solution.

**Pull request merged**
