### PR TITLE
add workflow configuration object

### LINKED ISSUE #1454: add workflow configuration object
linked to #1452, allow per workflow configs

### PR DESCRIPTION
**Pull request by camallen**
closes #1454

### CODE REVIEW

**Comment by camallen** [comment]
@marten can you please have a look at this? @itsravenous has a use case for building on staging.

**Comment by itsravenous** [comment]
Thanks guys! Works great locally. Does stage need dbmigrating? Still get 422 when `PUT`ing workflow with `config` set. Sorry if I'm being impatient :)

**Comment by camallen** [comment]
the deploy process is happening..should be ready in 30 mins or so.

**Comment by itsravenous** [comment]
Great!

**Pull request merged**
