### PR TITLE
Optimize user login migration

### PR DESCRIPTION
**Pull request by camallen**
allow a list of display_name and only migrate users that don't have a login field set.

### CODE REVIEW

**Comment by edpaget** [comment]
Users can't have a missing login since the login column has a NOT NULL constraint.

**Comment by camallen** [comment]
I got rid of that here - https://github.com/zooniverse/Panoptes/pull/989/files

Needs to be added back in after the migration.

**Comment by edpaget** [comment]
iNo it's still there in that commit the `change_column :users, :login, :string, null: false` at the end.

**Comment by camallen** [comment]
sorry pasted the wrong link, https://github.com/zooniverse/Panoptes/pull/993/files

Looks like staging got this migration. Did you run it manually on your computer as the jenkins deploy logs just have a failure then a empty success? 

Production got the one I ran this morning to so that column now exists, no null constraint (validation is on the model) and owner and beta users have been migrated. The rest need to be run now.

**Comment by edpaget** [comment]
Yeah I ran the development migration in pretty much the same way you're doing it now. Should I kick of the rest of the migration?

**Pull request merged**
