### PR TITLE
dequeue subjects only once

### PR DESCRIPTION
**Pull request by camallen**
when the classification comes in and not when serving out as well.

### CODE REVIEW

**Comment by edpaget** [comment]
Can we do it the other way around? Otherwise we have the possiblity of duplicates from when the front-end requests more subjects before classifications have come in.

**Comment by camallen** [comment]
yep can do note that it too may have a race condition too where the queue is below min threshold and it kicks off an enqueue task that may requeue subjects that have just been selected

**Comment by camallen** [comment]
kinda sounds like we need both ends dequeing...

**Comment by chrissnyder** [comment]
PFE does track subjects seen in a given session. The only thing it affects is wether we display the badge "you already classified this" or not. We could look through the subjects returned from the API and prioritize ones that haven't been seen.

**Comment by camallen** [comment]
@chrissnyder how does that relate to https://github.com/zooniverse/Panoptes-Front-End/issues/1427?

**Comment by chrissnyder** [comment]
I think they are one in the same. We could apply that prioritization to both logged in and not logged in users. Basically just making https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L146 a bit smarter.

**Comment by camallen** [comment]
@edpaget what do you think about this? I'd like to not rely on clients having to track this data to ensure we don't get dups.

**Comment by camallen** [comment]
@chrissnyder - any ETA on the smarter subject session tracking?

**Comment by edpaget** [comment]
Yeah I don't think we should rely on clients at all for not showing dups.

**Comment by camallen** [comment]
closing in favour of #1327

**Pull request closed without merging**
